sudo: required

language: go
go:
  - 1.9

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - go env && pwd

install:
  - docker swarm init

script:
  - >
    go test ./... --run UnitTest -v &&
    docker image build -t thomasjpfan/docker-scaler:$TRAVIS_COMMIT . &&
    docker stack deploy -c scripts/docker-compose.yml test &&
    ./scripts/integration_test.sh

after_script:
  - docker stack rm test

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker tag thomasjpfan/docker-scaler:$TRAVIS_COMMIT thomasjpfan/docker-scaler:latest
      docker push thomasjpfan/docker-scaler:latest
    elif [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker tag thomasjpfan/docker-scaler:$TRAVIS_COMMIT thomasjpfan/docker-scaler:$TRAVIS_TAG
      docker push thomasjpfan/docker-scaler:$TRAVIS_TAG
    fi
